# Generated by Django 5.1.2 on 2024-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi_app', '0003_customer_supplier_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edimessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='edimessage',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('INVOICE', 'Invoice'), ('SHIPMENT', 'Shipment')], max_length=10),
        ),
    ]
